### ISSUE TITLE
Dune fails to build

### ISSUE THREAD

**Issue by rafael1193** [LSTS/dune#107]
Dune fails to build because of the following error:

CMake Error at cmake/Compiler.cmake:78 (list):       
  list index: 1 out of range (-1, 0)                 
Call Stack (most recent call first):                 
  cmake/Macros.cmake:41 (dune_probe_cxx)             
  cmake/Macros.cmake:82 (DUNE_PROBE_SYSTEM)          
  CMakeLists.txt:72 (include) 

I am using Fedora 26 with gcc (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2) and cmake version 3.9.1

**Comment by rasmartins** [comment]
Fixed in commit 84a731dc9dc06fad5af5c8d80f04e6e2a4bb9786.
