### ISSUE TITLE
Sporadic segmentation fault at startup

### ISSUE THREAD

**Issue by krisklau** [LSTS/dune#151]
We have discovered a bug causing sporadic segfaults at startup. It happens somewhat rare, but is very easy to reproduce. 

### Version to run
master (as of now 2a32fbe42d241bfa207681a75c46b69112c1bc65)

### Effect
Seg-fault. 

### How to reproduce 

1. Compile a debug-build of dune (`cmake -DDEBUG=True .`)
2. Build
3. Load gdb (`gdb dune`)
4. In the gdb prompt, do
   1. `set pagination off` (to let it auto continue)
   2. `break Logging/Task.cpp:369` (Set a breakpoint a bit after startup)
   3. `commands` (will give you a new prompt)
      1. `run`
      2. `end`
5. `run -c lauv-seacon-1 -p Simulation`

This will seg-fault quite fast. Depending on the machine, it will attempt the startup a couple of times a second.

**Comment by mariacosta** [comment]
Proposed solution (PR #152) was merged.
