### ISSUE TITLE
World magnetic model update (WMM2015v2)

### ISSUE THREAD

**Issue by oysstu** [LSTS/dune#166]
The world magnetic model (WMM) has received an out-of-cycle update to address performance degradation in the current model. A full WMM release should be made in 2020, but for now, this updated model should be used. I suggest updating the coefficients to the v2 version (etc/wmm/wmm.cof).

[https://www.ngdc.noaa.gov/geomag/WMM/soft.shtml](https://www.ngdc.noaa.gov/geomag/WMM/soft.shtml)

**Comment by zepinto** [comment]
Thanks, it has now been updated.
