### ISSUE TITLE
Fix AppVeyor build

### ISSUE THREAD

**Issue by mortenfyhn** [LSTS/dune#167]
The AppVeyor builds have been broken since April last year. As discussed in today's meeting I'll open this issue to make the case more visible.

**Comment by mortenfyhn** [comment]
Note: I do not have the required permissions to add labels to this issue, so I cannot mark it with a `priority` label or similar. Actually I don't think there is a priority label defined. (I cannot add labels to pull requests either.)

**Comment by zepinto** [comment]
Fixed in master.
