### ISSUE TITLE
Windows compilation

### ISSUE THREAD

**Issue by zepinto** [LSTS/dune#214]
Currently, DUNE fails to compile in windows for trying to use 'unsigned long long' types:

```libSimulators.StreamVelocity.a(ModelDataStreamGenerator.cpp.obj):ModelDataStreamGenerator.cpp:(.text+0x62b): undefined reference to `std::vector<unsigned long long, std::allocator<unsigned long long> > DUNE::Parsers::HDF5Reader::getAttribute<unsigned long long>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
collect2: error: ld returned 1 exit status```.

MinGW cross-compilation toolchain (for testing):
 * https://gist.github.com/zepinto/dbbe84fa4ca6e7f59954adabc5bc3dcc

**Comment by mcpca** [comment]
Just pushed a fix to bugfix/hdf5-win, I'm able to build on mingw and x64_64 Linux.
Could you confirm that it works for you?

**Comment by zepinto** [comment]
Yes, this fixes the problem. Will merge to master.
