### ISSUE TITLE
imc_blob.py: 'ElementTree' object has no attribute 'getiterator'

### ISSUE THREAD

**Issue by oysstu** [LSTS/dune#225]
The getiterator function is deprecated since Python 3.2 and is removed in Python 3.9. The replacement is tree.iter().

https://github.com/LSTS/dune/blob/93a49ab28464a8354feb77d7f02223f8d129103b/programs/generators/imc_blob.py#L69

**Comment by paulosousadias** [comment]
Thanks. Fixed in ce41d1bdb.
