### ISSUE TITLE
Transports.Seatract - Compilation erro in Visual Studio

### ISSUE THREAD

**Issue by AndreGCGuerra** [LSTS/dune#70]
Hello,
Just wanted to let you know that to compile Dune in Windows Visual Studio you have to add to the Transports.Seatrack Task "#include <iterator>".
Otherwise you get an error std::back_inserter

Just a heads up.

Regards,
André

**Comment by rasmartins** [comment]
Can you submit a PR with the fix ?

**Comment by AndreGCGuerra** [comment]
Sure. No problem.
