### ISSUE TITLE
Using database for storing IMC messages instead of gziped LSF 

### ISSUE THREAD

**Issue by TobiasWernerJHS** [LSTS/dune#94]
Hello,

I was wondering, that IMC messages in terms of sensor data will be stored as gziped LSF file instead of using the build in SQLite database. Are there certain reasons for avoiding the database? If im right, SQLite is only used for mission planning currently.

**Comment by josebraga** [comment]
Hello

We do not access past data as a general rule. Any task that needs to do it can use a DB locally
Also, since we only write, I suppose DB is less efficient due to possible overheads, and, I am not totally sure if it wouldn't mean higher memory usage..

**Comment by TobiasWernerJHS** [comment]
Thank you.
